# Generated by Django 5.2 on 2025-05-13 16:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_gender_genderid_alter_otpdata_otpdataid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportCategory',
            fields=[
                ('SportCategoryID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('SportCategory', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'SportCategory',
            },
        ),
        migrations.AlterField(
            model_name='gender',
            name='GenderID',
            field=models.UUIDField(default=uuid.UUID('add0c1d7-5379-49f1-9e68-2f754ccdeb6d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='otpdata',
            name='OTPDataID',
            field=models.UUIDField(default=uuid.UUID('e10de905-6556-47c9-81f3-c7846e871776'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='PaymentTypeID',
            field=models.UUIDField(default=uuid.UUID('29b0eaa4-ba63-4151-978e-4899e2d326f3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
