# Generated by Django 5.2 on 2025-05-14 16:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_sportcategory_alter_gender_genderid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='GenderID',
            field=models.UUIDField(default=uuid.UUID('296c7363-a29b-41c3-9d65-73ffecd7b1fe'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='otpdata',
            name='OTPDataID',
            field=models.UUIDField(default=uuid.UUID('23bbcb79-6572-4e1a-823b-958b7c8ade9b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='PaymentTypeID',
            field=models.UUIDField(default=uuid.UUID('12681ccd-c6df-4caa-b378-80fc13d93c64'), editable=False, primary_key=True, serialize=False),
        ),
    ]
