# Generated by Django 5.2 on 2025-05-14 16:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_gender_genderid_alter_otpdata_otpdataid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='GenderID',
            field=models.UUIDField(default=uuid.UUID('1822b65d-69ac-4c71-a695-63103ba91aac'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='otpdata',
            name='OTPDataID',
            field=models.UUIDField(default=uuid.UUID('7fe21686-6970-4769-b9b4-aeb44b91dc71'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='PaymentTypeID',
            field=models.UUIDField(default=uuid.UUID('3230652b-c50f-4591-b7c0-8ae3f54e8d60'), editable=False, primary_key=True, serialize=False),
        ),
    ]
