# Generated by Django 5.2 on 2025-05-14 16:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_gender_genderid_alter_otpdata_otpdataid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='GenderID',
            field=models.UUIDField(default=uuid.UUID('b160c2c0-e52c-42e2-9b8d-62a470a8c0f8'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='otpdata',
            name='OTPDataID',
            field=models.UUIDField(default=uuid.UUID('02c41d7b-d2b8-4ea7-8d8e-dc6ad5aad8da'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='PaymentTypeID',
            field=models.UUIDField(default=uuid.UUID('deeeec6b-2f6c-4b03-a3cb-0ca6c7dee0bd'), editable=False, primary_key=True, serialize=False),
        ),
    ]
