# Generated by Django 5.2 on 2025-05-14 16:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_gender_genderid_alter_otpdata_otpdataid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='GenderID',
            field=models.UUIDField(default=uuid.UUID('8019cc69-3a49-4c1b-84bf-fe8ead18ce27'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='otpdata',
            name='OTPDataID',
            field=models.UUIDField(default=uuid.UUID('63183d24-2071-49c5-b063-c8032d9cdcb2'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='PaymentTypeID',
            field=models.UUIDField(default=uuid.UUID('e778dac5-71a3-4121-b4ad-4a326d965954'), editable=False, primary_key=True, serialize=False),
        ),
    ]
