# Generated by Django 5.2 on 2025-05-15 16:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_gender_genderid_alter_otpdata_otpdataid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='GenderID',
            field=models.UUIDField(default=uuid.UUID('cb869686-7a17-4d00-9d14-efda222e2c36'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='otpdata',
            name='OTPDataID',
            field=models.UUIDField(default=uuid.UUID('1ceec526-a6f9-4548-ad4e-bdee99ca72bd'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='PaymentTypeID',
            field=models.UUIDField(default=uuid.UUID('a2ca64b5-1164-4469-add4-3ff1384863d9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
