# Generated by Django 5.2 on 2025-05-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_gender_genderid_alter_otpdata_otpdataid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='ProfileImage',
            field=models.ImageField(blank=True, null=True, upload_to='profile_img'),
        ),
    ]
