# Generated by Django 5.2 on 2025-06-14 06:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_users_profileimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('NotificationID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('Message', models.TextField()),
                ('Date', models.DateField()),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('User', models.ForeignKey(db_column='UserID', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Notification',
            },
        ),
    ]
