# Generated by Django 5.2 on 2025-05-17 11:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0001_initial'),
        ('mainapp', '0009_alter_gender_genderid_alter_otpdata_otpdataid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('ReelID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Video', models.FileField(upload_to='reels_videos/')),
                ('Thumbnail', models.ImageField(blank=True, null=True, upload_to='reels_thumbnails/')),
                ('Date', models.DateField(auto_now_add=True)),
                ('Time', models.TimeField(auto_now_add=True)),
                ('IsActive', models.BooleanField(default=True)),
                ('Author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('Category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.sportcategory')),
            ],
            options={
                'db_table': 'Reel',
            },
        ),
    ]
