# Generated by Django 5.2 on 2025-04-26 18:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('StartTime', models.TimeField()),
                ('EndTime', models.TimeField()),
                ('IsActive', models.BooleanField(default=True)),
                ('SpecialRate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Availabilities',
                'db_table': 'Availability',
            },
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('CourtID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('SurfaceType', models.CharField(choices=[('artificial_grass', 'Artificial Grass'), ('concrete', 'Concrete'), ('wood', 'Wood')], max_length=20)),
                ('Capacity', models.PositiveIntegerField()),
                ('HourlyRate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('IsActive', models.BooleanField(default=False)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Court',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('BookingID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('TotalPrice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Notes', models.TextField(blank=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('Availability', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='venue.availability')),
                ('PaymentMethod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.paymenttype')),
                ('Status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.status')),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Booking',
            },
        ),
        migrations.AddField(
            model_name='availability',
            name='Court',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='availabilities', to='venue.court'),
        ),
        migrations.CreateModel(
            name='CourtImages',
            fields=[
                ('ImageID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='court_images/')),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('Court', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courts_images', to='venue.court')),
            ],
            options={
                'db_table': 'CourtImages',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('PaymentTransactionID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('TransactionID', models.CharField(max_length=100, unique=True)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('RawResponse', models.JSONField(blank=True, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('Booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='venue.booking')),
                ('PaymentMethod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.paymenttype')),
                ('PaymentStatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.status')),
            ],
            options={
                'db_table': 'PaymentTransaction',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('VenueID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('Address', models.TextField()),
                ('Latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('Longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('PhoneNumber', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=254)),
                ('Description', models.TextField(blank=True)),
                ('OpeningTime', models.TimeField()),
                ('ClosingTime', models.TimeField()),
                ('IsActive', models.BooleanField(default=False)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('City', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.city')),
                ('Owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venue_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Venue',
            },
        ),
        migrations.CreateModel(
            name='OnlinePaymentKhaltiSecretKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('SecretKey', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Venue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='khalti_keys', to='venue.venue')),
            ],
            options={
                'db_table': 'OnlinePaymentKhaltiSecretKey',
            },
        ),
        migrations.AddField(
            model_name='court',
            name='Venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venue', to='venue.venue'),
        ),
        migrations.CreateModel(
            name='VenueApplication',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('VenueName', models.CharField(max_length=100)),
                ('Address', models.TextField()),
                ('PhoneNumber', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=254)),
                ('PanNumber', models.CharField(max_length=50)),
                ('Status', models.CharField(choices=[('pending', 'Pending'), ('Under Review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('AdminRemark', models.TextField(blank=True, null=True)),
                ('IsActive', models.BooleanField(default=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('Applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venue_applications', to=settings.AUTH_USER_MODEL)),
                ('City', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.city')),
            ],
            options={
                'db_table': 'VenueApplication',
            },
        ),
        migrations.CreateModel(
            name='VenueApplicationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('DocumentType', models.CharField(choices=[('PAN Card', 'PAN Card'), ('Government Approval', 'Government Approval'), ('Business License', 'Business License'), ('Other', 'Other')], max_length=20)),
                ('DocumentFile', models.FileField(upload_to='venue_documents/')),
                ('UploadedAt', models.DateTimeField(auto_now_add=True)),
                ('Application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='venue.venueapplication')),
            ],
            options={
                'db_table': 'VenueApplicationDocument',
            },
        ),
        migrations.CreateModel(
            name='VenueImages',
            fields=[
                ('ImageID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='venue_images/')),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('Venue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venue_images', to='venue.venue')),
            ],
            options={
                'db_table': 'VenueImages',
            },
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('Court', 'Date', 'StartTime', 'EndTime')},
        ),
    ]
