# Generated by Django 5.2 on 2025-05-13 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_sportcategory_alter_gender_genderid_and_more'),
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='SportCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.sportcategory'),
        ),
    ]
