# Generated by Django 5.2 on 2025-05-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0002_court_sportcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='ClosingTime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='OpeningTime',
            field=models.TimeField(null=True),
        ),
    ]
