# Generated by Django 5.2 on 2025-05-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0003_alter_venue_closingtime_alter_venue_openingtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venueapplication',
            name='Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=30),
        ),
    ]
