# Generated by Django 5.2 on 2025-05-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0004_alter_venueapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='Description',
            field=models.TextField(blank=True),
        ),
    ]
