# Generated by Django 5.2 on 2025-06-14 06:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0005_court_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='SurfaceType',
            field=models.CharField(choices=[('Artificial Grass', 'Artificial Grass'), ('Concrete', 'Concrete'), ('Wood', 'Wood')], max_length=20),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('EventId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('MaximunSeat', models.PositiveIntegerField()),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Court', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='venue.court')),
            ],
            options={
                'db_table': 'Event',
            },
        ),
        migrations.CreateModel(
            name='EventRegisteredRecord',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='venue.event')),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'EventRegisteredRecord',
            },
        ),
    ]
