# Generated by Django 5.2 on 2025-06-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0006_alter_court_surfacetype_event_eventregisteredrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='TotalPrice',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='Booking',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='Bookings',
            field=models.ManyToManyField(related_name='transactions', to='venue.booking'),
        ),
    ]
