# Generated by Django 5.2 on 2025-06-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0007_remove_booking_totalprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='TotalPrice',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
