# Generated by Django 5.2 on 2025-06-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0008_booking_totalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='EventTitle',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
