# Generated by Django 5.2 on 2025-06-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0009_event_eventtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Image',
            field=models.ImageField(null=True, upload_to='events_image/'),
        ),
    ]
