# Generated by Django 5.2 on 2025-07-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0010_event_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlinepaymentkhaltisecretkey',
            old_name='SecretKey',
            new_name='PrivateSecretKey',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='TransactionID',
        ),
        migrations.AddField(
            model_name='onlinepaymentkhaltisecretkey',
            name='PublicSecretKey',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='TokenID',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
