# Generated by Django 5.2 on 2025-07-16 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0011_rename_secretkey_onlinepaymentkhaltisecretkey_privatesecretkey_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinepaymentkhaltisecretkey',
            name='PublicSecretKey',
        ),
    ]
