# Generated by Django 5.2 on 2025-07-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0012_remove_onlinepaymentkhaltisecretkey_publicsecretkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregisteredrecord',
            name='Token',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
